# files: os/tasks/timezone.yml

- name: TIMEZONE | os/tasks/timezone.yml(copy /etc/localtime)
  copy:
    src  : /usr/share/zoneinfo/{{ timezone }}
    dest : /etc/localtime
    owner: root
    group: root
    mode : 644
    force: yes

- name: TIMEZONE | os/tasks/timezone.yml(rewrite /etc/sysconfig/clock)
  lineinfile:
    dest    : /etc/sysconfig/clock
    state   : present
    backrefs: yes
    regexp  : '^ZONE=\"UTC\"'
    line    : 'ZONE="{{ timezone }}"'
